config/routes.rb
MonoOki::Application.routes.draw do
  root :to => 'apks#index'
  resources :apks
end

app/models/apk.rb
class Apk < ActiveRecord::Base
  attr_accessible :desc, :link, :memo, :tag, :title
end

app/controllers/apks_controller.rb
class ApksController < ApplicationController
  # GET /apks
  # GET /apks.json
  def index
    @apks = Apk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apks }
    end
  end

  # GET /apks/1
  # GET /apks/1.json
  def show
    @apk = Apk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @apk }
    end
  end

  # GET /apks/new
  # GET /apks/new.json
  def new
    @apk = Apk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @apk }
    end
  end

  # GET /apks/1/edit
  def edit
    @apk = Apk.find(params[:id])
  end

  # POST /apks
  # POST /apks.json
  def create
    file_path = save_apk_file(params[:apk][:file])

    uploaded_apk = params[:apk]
    uploaded_apk.delete(:file)
    uploaded_apk[:link] = file_path

    @apk = Apk.new(uploaded_apk)

    respond_to do |format|
      if @apk.save
        format.html { redirect_to @apk, notice: 'Apk was successfully created.' }
        format.json { render json: @apk, status: :created, location: @apk }
      else
        format.html { render action: "new" }
        format.json { render json: @apk.errors, status: :unprocessable_entity }
      end
    end
  end

  def save_apk_file(apk_file)
    base_path = Rails.root.to_s + "/public"
    file_path = "/apks/" + apk_file.original_filename
    File.binwrite(base_path + file_path, apk_file.read)
    return file_path
  end

  # PUT /apks/1
  # PUT /apks/1.json
  def update
    @apk = Apk.find(params[:id])

    respond_to do |format|
      if @apk.update_attributes(:tag => params[:tag])
        format.html { redirect_to @apk, notice: 'Apk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @apk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apks/1
  # DELETE /apks/1.json
  def destroy
    @apk = Apk.find(params[:id])
    @apk.destroy

    respond_to do |format|
      format.html { redirect_to apks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/apks_helper.rb
module ApksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apks/_form.html.haml
= form_for @apk do |f|
  - if @apk.errors.any?
    #error_explanation
      %h2= "#{pluralize(@apk.errors.count, "error")} prohibited this apk from being saved:"
      %ul
        - @apk.errors.full_messages.each do |msg|
          %li= msg

  .upload_input
    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :desc
      = f.text_area :desc, :class => 'desc_input_area'
    .field
      = f.label "apk"
      = f.file_field :file
  .upload_send
    .actions
      = f.submit 'Save', :class => 'btn'

app/views/apks/edit.html.haml
%h1 Editing apk

= render 'form'

= link_to 'Show', @apk
\|
= link_to 'Back', apks_path

app/views/apks/index.html.haml
%h1 MonoOki

.entry_app_list
  - @apks.each do |apk|
    .well{:data => {:tag => apk.tag}}
      %span.apk_title
        = link_to apk.title, apk
      %span.apk_delete_link
        = link_to '×', apk, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %hr
      .apk_desc
        = apk.desc
      %span.apk_download_link.btn{:data => {:id => apk.id, :download_link => apk.link}}
        download
%br

= link_to 'Upload Apk', new_apk_path

app/views/apks/new.html.haml
%h1 Upload apk

= render 'form'

= link_to 'Back', apks_path

app/views/apks/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @apk.title
%p
  %b Desc:
  = @apk.desc
%p
  %b Link:
  = @apk.link
%p
  %b Tag:
  = @apk.tag
%p
  %b Memo:
  = @apk.memo

= link_to 'Edit', edit_apk_path(@apk)
\|
= link_to 'Back', apks_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonoOki</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "apks", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>